export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CURRENT_ACCOUNT = 'CURRENT_ACCOUNT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_ERROR = 'GET_ALL_NEWS_ERROR';

export const GET_ONE_NEWS = 'GET_ONE_NEWS';
export const GET_ONE_NEWS_SUCCESS = 'GET_ONE_NEWS_SUCCESS';
export const GET_ONE_NEWS_ERROR = 'GET_ONE_NEWS_ERROR';

export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_ERROR = 'GET_ALL_MOVIES_ERROR';

export const GET_SHOWING_MOVIES = 'GET_SHOWING_MOVIES';
export const GET_SHOWING_MOVIES_SUCCESS = 'GET_SHOWING_MOVIES_SUCCESS';
export const GET_SHOWING_MOVIES_ERROR = 'GET_SHOWING_MOVIES_ERROR';

export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_ERROR = 'GET_UPCOMING_MOVIES_ERROR';

export const GET_ONE_MOVIE = 'GET_ONE_MOVIE';
export const GET_ONE_MOVIE_SUCCESS = 'GET_ONE_MOVIE_SUCCESS';
export const GET_ONE_MOVIE_ERROR = 'GET_ONE_MOVIE_ERROR';