export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CURRENT_ACCOUNT = 'CURRENT_ACCOUNT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_ALL_NEWS = 'GET_ALL_NEWS';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_ERROR = 'GET_ALL_NEWS_ERROR';

export const GET_ONE_NEWS = 'GET_ONE_NEWS';
export const GET_ONE_NEWS_SUCCESS = 'GET_ONE_NEWS_SUCCESS';
export const GET_ONE_NEWS_ERROR = 'GET_ONE_NEWS_ERROR';

export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_ERROR = 'GET_ALL_MOVIES_ERROR';

export const GET_SHOWING_MOVIES = 'GET_SHOWING_MOVIES';
export const GET_SHOWING_MOVIES_SUCCESS = 'GET_SHOWING_MOVIES_SUCCESS';
export const GET_SHOWING_MOVIES_ERROR = 'GET_SHOWING_MOVIES_ERROR';

export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_ERROR = 'GET_UPCOMING_MOVIES_ERROR';

export const GET_ONE_MOVIE = 'GET_ONE_MOVIE';
export const GET_ONE_MOVIE_SUCCESS = 'GET_ONE_MOVIE_SUCCESS';
export const GET_ONE_MOVIE_ERROR = 'GET_ONE_MOVIE_ERROR';

export const GET_MOVIE_BY_SCHEDULE = 'GET_MOVIE_BY_SCHEDULE';
export const GET_MOVIE_BY_SCHEDULE_SUCCESS = 'GET_MOVIE_BY_SCHEDULE_SUCCESS';
export const GET_MOVIE_BY_SCHEDULE_ERROR = 'GET_MOVIE_BY_SCHEDULE_ERROR';

export const GET_TICKET = 'GET_TICKET';
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR';

export const GET_SEAT = 'GET_SEAT';
export const GET_SEAT_SUCCESS = 'GET_SEAT_SUCCESS';
export const GET_SEAT_ERROR = 'GET_SEAT_ERROR';

export const UPDATE_TICKET = 'UPDATE_TICKET';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_ERROR = 'UPDATE_TICKET_ERROR';

export const BOOK = 'BOOK'
export const BOOK_SUCCESS = 'BOOK_SUCCESS';
export const BOOK_ERROR = 'BOOK_ERROR';

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';

export const RESET_TICKET = 'RESET_TICKET';
export const RESET_TICKET_SUCCESS = 'RESET_TICKET_SUCCESS';
export const RESET_TICKET_ERROR = 'RESET_TICKET_ERROR';

export const GET_MOVIE_ADMIN = 'GET_MOVIE_ADMIN';
export const GET_MOVIE_ADMIN_SUCCESS = 'GET_MOVIE_ADMIN_SUCCESS';
export const GET_MOVIE_ADMIN_ERROR = 'GET_MOVIE_ADMIN_ERROR';

export const GET_SCHEDULE_ADMIN = 'GET_SCHEDULE_ADMIN';
export const GET_SCHEDULE_ADMIN_SUCCESS = 'GET_SCHEDULE_ADMIN_SUCCESS';
export const GET_SCHEDULE_ADMIN_ERROR = 'GET_SCHEDULE_ADMIN_ERROR';

export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR';